#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "mpp_neutral_score_distribution_model.json"
TARGET = ROOT / "extension" / "neutral-score-model.js"


def main() -> None:
    model = json.loads(SOURCE.read_text())
    distributions = {
        key: {
            "samples": value["match_issue_samples"],
            "scores": {
                score["relative_score"]: score["probability"]
                for score in value["scores"]
            },
        }
        for key, value in model["distributions"].items()
    }
    payload = json.dumps({"distributions": distributions}, ensure_ascii=True, separators=(",", ":"))
    TARGET.write_text(
        "// Generated by scripts/export_neutral_model_to_extension.py\n"
        f"globalThis.MPP_NEUTRAL_SCORE_MODEL={payload};\n"
    )
    print(TARGET)


if __name__ == "__main__":
    main()
